### ISSUE TITLE
Morning session peer to peer code review

### ISSUE THREAD

**Issue by aster-alemu** [SSEKPIUS/Microverse-ToDo-list#11]
Hi @SSEKPIUS 👋
**Highlights:**
- Your project page is looking fantastic so far 🤩 !
- You used Gitflow correctly 👍
- Linter checks passed 👍
- Used ES Modules correctly as required 👍
- Your app works fine as expected 👍
However, there is still some room for improvement, your live demo is not working and kindly work on it

**Comment by SSEKPIUS** [comment]
@aster-alemu , thank you for the review, live demo link is updated.
